# Generated by Django 4.2.3 on 2023-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Создание'),
        ),
    ]
